/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsStreamex {
  constructor()
  trades(exchange: string, symbol: string, callback: (arg: string) => void): void
  disconnect(exchange: string): void
}
